#! /bin/sh

sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true


bspc rule -a Firefox desktop='^1'
bspc rule -a Thunar desktop='^4'
bspc rule -a Chromium desktop='^5'
bspc rule -a Chromium-browser desktop='^5' follow=false
bspc rule -a Zathura desktop='^6'
bspc rule -a Gpicview desktop='^6'
bspc rule -a vlc desktop='^7'
bspc rule -a telegram-desktop desktop='^8'

bspc rule -a Lxappearance state=floating
bspc rule -a Thunar state=floating
bspc rule -a Seahorse state=floating
bspc rule -a telegram-desk state=floating

$HOME/.config/polybar/launch.sh
